#include <iostream.h>
#include <conio.h>
#include <math.h>
int main()
{
int a;
cout<<"enter a value- 1. increasing order 2.decreasing error";
}
else if(a=1)
{
increase();
cout<<"quicksort implemented in increasing order";
}
else if(a=2)
{
decrease();
cout<<"Quick sort implemented in decresing order";
}
else
{
cout<<"Wrong number entered";
}
void increase()
{
int a,b,c;
a=3;
b=5;
c=7;
if(a>b&&b>c)
{
cout<<c,b,a;
}
elserif(a<b&&b<c)
{
cout<<a,b,c;
}
}
void decrease()
{
int d,e,f;
d=7;
e=8
f=9;
if(d>e&&e>f)
{
cout<<f,e,d;
}
else if(d<e&&e>f)
{
cout<<d,e,f;
}
}
}
